# HOMEWORK 5
### İlkan Mert Okul, 1801042649

## **Part 1**
### *Select a dataset, i choosed IRIS dataset from sklearn datasets*

In [184]:
import sklearn as sk
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt 
import numpy as np
import tensorflow_datasets

from sklearn.neural_network import MLPClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.ensemble import AdaBoostClassifier

In [185]:
iris = sk.datasets.load_iris()

trainX = iris.data
targetY = iris.target

## **Part 2**
### Train a MLP, experiment with at least 3 different depths and different number of nodes in each.

Test 1 -> hidden_layer_sizes = 2, 4  -- alpha = 0.1 

In [186]:
clf = MLPClassifier(solver='lbfgs', alpha=0.1, hidden_layer_sizes=(2 ,4, ), random_state=1).fit(trainX,targetY)

prediction = clf.predict(trainX)

confusion_matrix(prediction,targetY)

array([[50,  0,  0],
       [ 0, 49,  0],
       [ 0,  1, 50]])

Test 2 -> hidden_layer_sizes = 3, 3 -- alpha = 1e-5

In [187]:
clf = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(3, 3, ), random_state=1).fit(trainX,targetY)

prediction = clf.predict(trainX)

confusion_matrix(prediction,targetY)

array([[50,  0,  0],
       [ 0, 47,  0],
       [ 0,  3, 50]])

Test 3 -> hidden_layer_sizes = 5, 5, 2 -- alpha = 0.5 -- max_iter = 700

In [188]:
clf = MLPClassifier(solver='lbfgs', alpha=0.5, hidden_layer_sizes=(5, 5, 2), random_state=1, max_iter = 700).fit(trainX,targetY)

prediction = clf.predict(trainX)

confusion_matrix(prediction,targetY)

array([[50,  0,  0],
       [ 0, 49,  1],
       [ 0,  1, 49]])

## Part 3
### Train a MLP, use a hidden layer perceptron as your base classifier to train an Adaboost ensemble learner.

In [264]:
# This piece of code is not written by me. It is taken from internet, i made small adjustments
# to match my needs.

class customMLPClassifer(MLPClassifier):
    def resample_with_replacement(self, X_train, y_train, sample_weight):

        # normalize sample_weights if not already
        sample_weight = sample_weight / sample_weight.sum(dtype=np.float64)

        X_train_resampled = np.zeros((len(X_train), len(X_train[0])), dtype=np.float32)
        y_train_resampled = np.zeros((len(y_train)), dtype=np.int)
        for i in range(len(X_train)):
            # draw a number from 0 to len(X_train)-1
            draw = np.random.choice(np.arange(len(X_train)), p=sample_weight)

            # place the X and y at the drawn number into the resampled X and y
            X_train_resampled[i] = X_train[draw]
            y_train_resampled[i] = y_train[draw]

        return X_train_resampled, y_train_resampled


    def fit(self, X, y, sample_weight=None):

        self.solver = 'lbfgs'
        self.hidden_layer_sizes = 3
        self.max_iter = 700
        self.alpha = 0.5

        if sample_weight is not None:
            X, y = self.resample_with_replacement(X, y, sample_weight)

        return self._fit(X, y, incremental=(self.warm_start and
                                            hasattr(self, "classes_")))

### This is using Adaboost "SAMME.R" algorithm

In [265]:
adaboost = AdaBoostClassifier(base_estimator=customMLPClassifer().fit(X =trainX, y = targetY), n_estimators=3, algorithm="SAMME.R", learning_rate=0.5)

adaboost.fit(trainX,targetY)

adaPrediction = adaboost.predict(trainX)

confusion_matrix(adaPrediction,targetY)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Depreca

array([[50,  0,  0],
       [ 0, 49,  1],
       [ 0,  1, 49]])

SAMME.R algorithm with 

self.solver = 'lbfgs'
self.hidden_layer_sizes = 3
self.max_iter = 700
self.alpha = 0.5  MLPClassifier 

got 0.9866 accuracy.

### This is using Adaboost "SAMME" algorithm

In [267]:
adaboost = AdaBoostClassifier(base_estimator=customMLPClassifer().fit(X =trainX, y = targetY), n_estimators=3, algorithm="SAMME", learning_rate=0.5)

adaboost.fit(trainX,targetY)

adaPrediction = adaboost.predict(trainX)

confusion_matrix(adaPrediction,targetY)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Depreca

array([[50,  0,  0],
       [ 0, 49,  2],
       [ 0,  1, 48]])

SAMME algorithm with

self.solver = 'lbfgs' self.hidden_layer_sizes = 3 self.max_iter = 700 self.alpha = 0.5 MLPClassifier

got 0.98 accuracy.